In [4]:
import torch
from torch import nn

import torchvision
from torchvision import datasets
from torchvision.transforms import ToTensor
from torch.utils.data import DataLoader

import matplotlib.pyplot as plt

from timeit import default_timer as timer
import numpy as np
import pandas as pd

In [6]:
Image = np.array([
    [0, 0, 0],
    [0, 3, 4],
    [0, 1, 7]
])
Image

array([[0, 0, 0],
       [0, 3, 4],
       [0, 1, 7]])

In [7]:
Filter = np.array([
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]
])
Filter

array([[ 0, -1,  0],
       [-1,  5, -1],
       [ 0, -1,  0]])

In [12]:
product = Filter.dot(Image)
product

array([[ 0, -3, -4],
       [ 0, 14, 13],
       [ 0, -3, -4]])

In [13]:
#### ignore top, it is wrong since we arent doing dot product, we need to shift our filter and provide single outputs making a 4x4

In [37]:
# here, using project2_vision for guideline 

conv = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 3, stride = 2, padding = 1, bias = False)

# A torch.Tensor is a multi-dimensional matrix containing elements of a single data type. 
# Please see torch.dtype for more details about dtype support.
# https://docs.pytorch.org/docs/stable/tensors.html
Filter = torch.tensor([[
    [
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]
    ]
]]).float()

image = torch.tensor([[
    [
    [3, 4, 2, 5, 6, 2, 3],
    [1, 7, 2, 3, 3, 6, 7],
    [2, 5, 3, 6, 5, 5, 6],
    [2, 4, 4, 7, 6, 7, 5],
    [3, 6, 3, 6, 7, 8, 6],
    [4, 5, 5, 5, 7, 6, 7],
    [6, 4, 3, 6, 6, 7, 7]
    ]
]]).float()

conv.weight.data = Filter
output = conv(image)

print(output[0][0])

tensor([[10., -1., 20.,  6.],
        [ 2., -2.,  5., 13.],
        [ 3., -6.,  8., 10.],
        [22.,  0., 10., 21.]], grad_fn=<SelectBackward0>)


In [ ]:
# class ConvModel(nn.Module):
#     def __init__(self, input_size, output_size):
#         # TODO: complete this method
#         super().__init__()

#         hidden_size = 32
#         self.conv1 = nn.Conv2d(in_channels = input_size, out_channels = hidden_size, 
#                               kernel_size = 3, stride = 1, padding = 1)
        
#         self.conv2 = nn.Conv2d(in_channels = hidden_size, out_channels = hidden_size, 
#                               kernel_size = 3, stride = 1, padding = 1)
        
#         self.relu = nn.ReLU()
#         self.pool = nn.MaxPool2d(kernel_size = 2, stride = 2)

#         self.fc_1 = nn.Linear(hidden_size * 7 * 7, 128)
#         self.fc_2 = nn.Linear(128, output_size)

#         self.flatten = nn.Flatten()
        

#     def forward(self, x):
#         # TODO: complete this method
#         x = self.relu(self.conv1(x))
#         x = self.pool(x)
        
#         x = self.relu(self.conv2(x))
#         x = self.pool(x)
        
#         x = self.flatten(x)
        
#         x = self.relu(self.fc_1(x))
#         x = self.fc_2(x)

#         return x

In [38]:
# using this as guidance from project2_vision 

In [41]:
pool = nn.MaxPool2d(kernel_size = 4, stride = 1)

image = torch.tensor([[
    [
    [3, 4, 2, 5, 6, 2, 3],
    [1, 7, 2, 3, 3, 6, 7],
    [2, 5, 3, 6, 5, 5, 6],
    [2, 4, 4, 7, 6, 7, 5],
    [3, 6, 3, 6, 7, 8, 6],
    [4, 5, 5, 5, 7, 6, 7],
    [6, 4, 3, 6, 6, 7, 7]
    ]
]]).float()

output = pool(image)

print(output)

tensor([[[[7., 7., 7., 7.],
          [7., 7., 8., 8.],
          [7., 7., 8., 8.],
          [7., 7., 8., 8.]]]])
