# Homework 1:


## Q1:

$\ x = \begin{pmatrix}x1 \\ x2 \end{pmatrix} in  R^2$
,

$
\begin{equation}
   \begin{bmatrix} 
   1 & 1 & -0.8  \\
   -1 & -2 & 0.1  \\
   2 & -1 & -5.0  \\
   \end{bmatrix} 
\end{equation}
$
,

$ \begin{equation}
   y^{hat} = w_0 + w_1x_1 + w_2x_2
\end{equation} 
$

#### A) 

$ T = 4, \alpha = 0.05, (w_0, w_1, w_2) = (0, 0, 0) $

$ (x_1, x_2, x_3) $

1: $ (1, 1, -0.8) $

2: $ -1, -2, 0.1) $

3: $ (2, -1, -5.0) $

$y^{hat(1)} = 0 + 0(1) + 0(1) = 0 $

$y^{hat(2)} = 0 + 0(-1) + 0(-2) = 0 $

$y^{hat(3)} = 0 + 0(2) + 0(-1) = 0 $

errors: ($ y^{hat} - y $)
- $y^{hat(1)}: 0 - (-0.8) = 0.8 $
- $y^{hat(2)}: 0 - 0.1 = -0.1 $
- $y^{hat(3)}: 0 - (-5.0) = 5.0 $

In [18]:
import numpy as np
import pandas as pd

In [19]:
x = np.array([
    [1, 1],
    [-1, -2],
    [2, -1]
])

y = np.array([-0.8, 0.1, -5.0])

w0, w1, w2 = 0.0, 0.0, 0.0
alpha = 0.05
n = len(y)

for i in range(1, 5): #running 4 iterations
    y_hat = w0 + (w1 * x[:, 0]) + (w2 * x[:, 1])
    error = y_hat - y
    mean_squared_error = np.mean(error ** 2)
    gradient1 = (2/n) * np.sum(error)
    gradient2 = (2/n) * np.sum(error * x[:, 0])
    gradient3 = (2/n) * np.sum(error * x[:, 1])
    w0 = w0 - alpha * gradient1
    w1 = w1 - alpha * gradient2
    w2 = w2 - alpha * gradient3
    print(w0, w1, w2, mean_squared_error)


-0.19 -0.36333333333333334 0.13333333333333333 8.549999999999999
-0.3278888888888889 -0.6457777777777778 0.23944444444444446 5.261425925925926
-0.4260851851851852 -0.8660777777777777 0.3245555555555556 3.31300890946502
-0.4941011111111111 -1.0386083950617284 0.3934413580246914 2.1533203291495204


In [20]:
X = np.array([
    [1, 1, 1],
    [1, -1, -2],
    [1, 2, -1]
])

xtx = X.T @ X
xtx_inverse = np.linalg.inv(xtx)

xty = X.T @ y

w = xtx_inverse @ xty

y_pred = X @ w

errors = y_pred - y 

total_error = np.sum(errors ** 2)

w, total_error
total_error

1.4860475450891912e-30

In [21]:
x1 = np.array([ [-5], [0], [1], [6] ])

x2 = np.array([
    [-5, 25],
    [0, 0],
    [1, 1],
    [6, 36]
])
#                                                   Equation: (xTx)^-1 xty
y1 = np.array([ [-6.2], [0.7], [2.5], [6.4] ])
y2 = np.array([ [-5.6], [0.6], [1.2], [7.2] ])

# x1 | y1, y2
x1tx1 = x1.T @ x1
x1tx1_inverse = np.linalg.inv(x1tx1)

x1ty1 = x1.T @ y1
x1ty2 = x1.T @ y2
w1 = x1tx1_inverse @ x1ty1
w2 = x1tx1_inverse @ x1ty2

# --------------------------------- #

# x2 | y1, y2
x2tx2 = x2.T @ x2
x2tx2_inverse = np.linalg.inv(x2tx2)

x2ty1 = x2.T @ y1
x2ty2 = x2.T @ y2
w3 = x2tx2_inverse @ x2ty1
w4 = x2tx2_inverse @ x2ty2

w1, w2, w3, w4

(array([[1.15967742]]),
 array([[1.16774194]]),
 array([[ 1.18360434],
        [-0.01612466]]),
 array([[1.15696477],
        [0.00726287]]))

In [22]:
xx = np.array([
    [1, 1],
    [2, -1],
    [-3, -1],
    [-3, 1]
])

yy = np.array([1, 0, 1, 1])

w = np.array([0, 0])

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def average_log_likelihood(w):
    log_likelihood = 0
    for a, b in zip(xx, yy):
        z = w @ a
        p = sigmoid(z)
        log_likelihood += b * np.log(p) + (1 - b) * np.log(1 - p)
    return log_likelihood / len(yy)


def gradient_ascent(alpha, n = 4):
    guesses = [np.array([0, 0])]
    current_guess = guesses[0]
    while len(guesses) < n + 1:
        gradient = np.array([0.0, 0.0])
        for a, b in zip(xx, yy):
            z = current_guess @ a
            p = sigmoid(z)
            gradient += (b - p) * a
        gradient = gradient / len(yy)
        current_guess = current_guess + alpha * gradient
        guesses.append(current_guess)
    return np.array(guesses)

In [23]:
iteration1 = gradient_ascent(0.01, n = 4)
iteration2 = gradient_ascent(0.2, n = 4)
w1 = iteration1[-1] #last element
w2 = iteration2[-1]
ll1 = average_log_likelihood(w1)
ll2 = average_log_likelihood(w2)


In [24]:
print(f"iteration 1: {iteration1}, w1: {w1}, average log likelihood: {ll1}")

iteration 1: [[ 0.          0.        ]
 [-0.00875     0.0025    ]
 [-0.01737266  0.00498828]
 [-0.02586987  0.00746496]
 [-0.03424349  0.00993015]], w1: [-0.03424349  0.00993015], average log likelihood: -0.6615776273762636


In [25]:
print(f"iteration 2: {iteration2}, w2: {w2}, average log likelihood: {ll2}")

iteration 2: [[ 0.          0.        ]
 [-0.175       0.05      ]
 [-0.30009838  0.09545861]
 [-0.39264224  0.13768578]
 [-0.46380564  0.17759553]], w2: [-0.46380564  0.17759553], average log likelihood: -0.3954420670938938


In [26]:
# import numpy as np

# probabilities = [0.9, 0.8, 0.3, 0.4]
# labels = [1, 1, 0, 0]

# log_likelihood = 0
# for p, y in zip(probabilities, labels):
#     log_likelihood += y * np.log(p) + (1 - y) * np.log(1 - p)

# print(f"Log Likelihood: {log_likelihood}")

#  from geeksforgeeks
# https://www.geeksforgeeks.org/data-science/log-likelihood/

In [27]:
# BELOW , DSCI 311 WEEK 6 HOMEWORK AND LECTURE FOR GRADIENT (DES)CENT, SIMILAR CODE TO ASCENT

In [ ]:
# def gradient_descent(df, initial_guess, alpha, n):
#     """Performs n steps of gradient descent on df using learning rate alpha starting
#        from initial_guess. Returns a numpy array of all guesses over time."""
#     guesses = [initial_guess]
#     current_guess = initial_guess
#     while len(guesses) < n:
#         current_guess = current_guess - alpha * df(current_guess)
#         guesses.append(current_guess)
        
#     return np.array(guesses)

#  from DSCI 311

In [ ]:
# def grad_desc(loss_f, gradient_loss_f, theta, num_iter=20, alpha=0.1):
#     """
#     Run gradient descent update for a finite number of iterations and static learning rate

#     Keyword arguments:
#     loss_f -- the loss function to be minimized (used for computing loss_history)
#     gradient_loss_f -- the gradient of the loss function to be minimized
#     theta -- the vector of values theta to use at first iteration
#     num_iter -- the max number of iterations
#     alpha -- the learning rate (also called the step size)
    
#     Return:
#     theta -- the optimal value of theta after num_iter of gradient descent
#     theta_history -- the series or array of theta values over each iteration of gradient descent
#     loss_history -- the series or array of loss values over each iteration of gradient descent
#     """
#     theta_history = []
#     loss_history = []
#     # while len(theta_history) < num_iter: values over each iteration, theta_history len will tell us the total amount of attempts 
        
#     #     loss = loss_f(theta)

#     #     theta_history.append(theta)
#     #     loss_history.append(loss)
    
#     while len(theta_history) <= num_iter: 
#         # had to put <= , since with < , it wasnt passing since
#         # len(thets_used) == 21 was returning False ,and not true 
        
#         loss = loss_f(theta)
#         theta_history.append(theta)
#         loss_history.append(loss)
        
#         theta = theta - alpha * (gradient_loss_f(theta))
        
#     return theta, theta_history, loss_history
    
# theta_start = init_theta()
# theta_hat, thetas_used, losses_calculated = grad_desc(sin_MSE, sin_MSE_gradient, theta_start, num_iter=20, alpha=0.1)
# for b, l in zip(thetas_used, losses_calculated):
#     print(f"theta: {b}, Loss: {l}")

In [ ]:
# def grad_desc_decay(loss_f, gradient_loss_f, theta, num_iter=20, alpha=0.1):
#     """
#     Run gradient descent update for a finite number of iterations and decaying learning rate

#     Keyword arguments:
#     loss_f -- the loss function to be minimized (used for computing loss_history)
#     gradient_loss_f -- the gradient of the loss function to be minimized
#     theta -- the vector of values theta to use at first iteration
#     num_iter -- the max number of iterations
#     alpha -- the learning rate (also called the step size)
    
#     Return:
#     theta -- the optimal value of theta after num_iter of gradient descent
#     theta_history -- the series or array of theta values over each iteration of gradient descent,
#                      should include the starting and ending theta (i.e. num_iter + 1 items)
#     loss_history -- the series or array of loss values over each iteration of gradient descent, 
#                      should include the starting and ending theta (i.e. num_iter + 1 items)
#     """
#     theta_history = []
#     loss_history = []

#     i = 0
#     while len(theta_history) < num_iter + 1:
#         loss = loss_f(theta)
        
#         theta_history.append(theta)
#         loss_history.append(loss)

#         theta = theta - (alpha / (i + 1)) * (gradient_loss_f(theta))

#         i += 1
        
#     return theta, theta_history, loss_history

# theta_start = init_theta()
# theta_hat_decay, thetas_used_decay, losses_calculated_decay =  grad_desc_decay(sin_MSE, sin_MSE_gradient, theta_start, num_iter=20, alpha=0.1)
# for b, l in zip(thetas_used_decay, losses_calculated_decay):
#     print(f"theta: {b}, Loss: {l}")

In [11]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [12]:
sigmoid(-1)

0.2689414213699951

In [28]:
y_prediction = sigmoid(-1)
(y_prediction - 1) ** 2

0.534446645388523

In [30]:
2 * (y_prediction - 1)

-1.4621171572600098

In [31]:
y_prediction * (1 - y_prediction)

0.19661193324148185

In [33]:
first = (2 * (y_prediction - 1)) * (y_prediction * (1 - y_prediction)) * 1
first

-0.28746968091443026

In [34]:
second = (2 * (y_prediction - 1)) * (y_prediction * (1 - y_prediction)) * 0
second

-0.0